East2West/Controllers/ClientFlightController.cs
using East2West.Data;
using East2West.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace East2West.Controllers
{
    public class ClientFlightController : Controller
    {
        private DBContext db = new DBContext();
        // GET: ClientHotel

        public ActionResult GetListFlight(string sortType, int? page, string destinationId, string departureId, int? status, string keyword, string price_range, DateTime? from_date, DateTime? to_date)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 5;
            ViewBag.SortType = sortType;
            ViewBag.Status = status;
            ViewBag.DepartureId = departureId;
            ViewBag.DestinationId = destinationId;
            ViewBag.PriceRange = price_range;
            ViewBag.Keyword = keyword;
            ViewBag.FromDate = from_date;
            ViewBag.ToDate = to_date;

            var flights = from f in db.Flights where f.Status != 0 select f;
            var locations = db.Locations.ToList();
            ViewBag.LocationList = db.Locations.ToList();

            flights = (status > 0) ? flights.Where(M => M.Status == status) : flights;

            if (!String.IsNullOrEmpty(destinationId))
            {
                flights = flights.Where(f => f.DestinationId == destinationId);
            }
            if (!String.IsNullOrEmpty(departureId))
            {
                flights = flights.Where(f => f.DepartureId == departureId);
            }
            if (!String.IsNullOrEmpty(keyword))
            {
                flights = flights.Where(f => f.LocationDestination.Name.Contains(keyword) || f.Description.Contains(keyword) || f.Detail.Contains(keyword) || f.LocationDeparture.Name.Contains(keyword));
            }
            if (from_date != null)
            {
                flights = flights.Where(f => f.DepartureAt >= from_date);
            }
            if (to_date != null)
            {
                flights = flights.Where(f => f.ReturnAt <= to_date);
            }

            switch (price_range)
            {
                case "all":
                    break;

                case "lt100":
                    flights = flights.Where(t => t.Price <= 100);
                    break;

                case "100to500":
                    flights = flights.Where(t => t.Price > 100 && t.Price <= 500);
                    break;

                case "500t1000":
                    flights = flights.Where(t => t.Price > 500 && t.Price <= 1000);
                    break;

                case "gt1000":
                    flights = flights.Where(t => t.Price > 1000);
                    break;

                default:
                    break;
            }

            switch (sortType)
            {
                case "createdAt_asc":
                    flights = flights.OrderBy(s => s.CreatedAt);
                    break;

                case "createdAt_desc":
                    flights = flights.OrderByDescending(s => s.CreatedAt);
                    break;

                case "duration_asc":
                    flights = flights.OrderBy(t => t.Duration);
                    break;

                case "duration_desc":
                    flights = flights.OrderByDescending(t => t.Duration);
                    break;

                default:
                    flights = flights.OrderBy(s => s.CreatedAt);
                    break;
            }

            return View(flights.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(string id)
        {
            ViewBag.UserId = Convert.ToString(System.Web.HttpContext.Current.User.Identity.GetUserId());
            if (id == null)
            {
                return RedirectToAction("Error404", "Home");
            }
            var flights = db.Flights.ToList();
            var locations = db.Locations.ToList();
            Flight flight = db.Flights.Where(M => M.Id == id).FirstOrDefault();
            var id_departure = flight.DepartureId;
            var id_destination = flight.DestinationId;
            var name_departure = locations.Find(x => x.Id == id_departure).Name;
            var name_destination = locations.Find(x => x.Id == id_destination).Name;

            if (flight == null)
            {
                return RedirectToAction("Error404", "Home");
            }
            ViewBag.LocationDeparture = name_departure ?? "";
            ViewBag.LocationDestination = name_destination ?? "";
            return View(flight);
        }
    }
}

East2West/Views/ClientFlight/Details.cshtml
@model East2West.Models.Flight

@{
    ViewBag.Title = "East2West - " + @ViewBag.LocationDeparture + "-" + @ViewBag.LocationDestination;
    Layout = "~/Views/Shared/_LayoutPageClient.cshtml";
}
@section Section
{
    @{
        var img = "https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg";
        if (Model.Thumbnail != null)
        {
            img = Model.Thumbnail.Split(',').ToList<String>().First();
        }
    }
    <section class="parallax-window" data-parallax="scroll" data-image-src="@img" data-natural-width="1400" data-natural-height="470">
        <div class="parallax-content-2">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h1>@ViewBag.LocationDeparture - @ViewBag.LocationDestination</h1>                        
                    </div>
                    <div class="col-md-4">
                        <div id="price_single_main">
                            From/Per flight <span><sup>$</sup>@Model.Price</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

<main>
    <div id="position">
        <div class="container">
            <ul>
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="@Url.Action("GetListFlight", "ClientFlight")">Flight</a>
                </li>
                <li>Detail</li>
            </ul>
        </div>
    </div>
    <!-- End Position -->

    <div class="collapse" id="collapseMap">
        <div id="map" class="map"></div>
    </div>
    <!-- End Map -->

    <div class="container margin_60">
        <div class="row">
            <div class="col-lg-12" id="single_tour_desc">
                <div id="single_tour_feat">
                    <ul>
                        <li><i class="icon_set_2_icon-116"></i>Plasma TV</li>
                        <li><i class="icon_set_1_icon-86"></i>Free Wifi</li>
                        <li><i class="icon_set_1_icon-59"></i>Meal</li>
                    </ul>
                </div>

                <!-- Map button for tablets/mobiles -->

                @{
                    if (Model.Thumbnail == null)
                    {
                        <div id="Img_carousel" class="slider-pro">
                            <div class="sp-slides">
                                <img alt="Image" class="sp-image" src="https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg" data-src="https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg" data-small="https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg" data-medium="https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg" data-large="https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg" data-retina="https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg">
                            </div>
                            <div class="sp-thumbnails">
                                <img alt="Image" class="sp-thumbnail" src="https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg">
                            </div>
                        </div>
                    }
                    else
                    {
                        var img = "https://res.cloudinary.com/nmqdec6/image/upload/v1655735551/Project%20East2West/default-thumbnail_bd4eth.jpg";
                        if (Model.Thumbnail != null)
                        {
                            img = Model.Thumbnail.Split(',').ToList<String>().First();
                        }
                        <div id="Img_carousel" class="slider-pro">
                            <div class="sp-slides">
                                <div class="sp-slide">
                                    <img alt="Image" class="sp-image" src="@img" data-src="@img" data-small="@img" data-medium="@img" data-large="@img" data-retina="@img">
                                </div>
                            </div>
                            <div class="sp-thumbnails">
                            </div>
                        </div>
                    }
                }

                <hr>

                <div class="row">
                    <div class="col-lg-3">
                        <h3>Detail:</h3>
                    </div>
                    <div class="col-lg-9">
                        @Html.Raw(HttpUtility.HtmlDecode(Model.Detail))
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-lg-3">
                        <h3>Departure At:</h3>
                    </div>
                    <div class="col-lg-9">
                        @Html.Raw(Model.DepartureAt)
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-lg-3">
                        <h3>Return At:</h3>
                    </div>
                    <div class="col-lg-9">
                        @Html.Raw(Model.ReturnAt)
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-lg-3">
                        <h3>Reviews </h3>
                        <a href="#" class="btn_1 add_bottom_30" data-bs-toggle="modal" data-bs-target="#myReview">Leave a review</a>
                    </div>
                    <div class="col-lg-9">
                        <div id="general_rating">
                            11 Reviews
                            <div class="rating">
                                <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i><i class="icon-smile"></i>
                            </div>
                        </div>
                        <!-- End general_rating -->
                        <div class="row" id="rating_summary">
                            <div class="col-md-6">
                                <ul>
                                    <li>
                                        Position
                                        <div class="rating">
                                            <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i><i class="icon-smile"></i>
                                        </div>
                                    </li>
                                    <li>
                                        Tourist guide
                                        <div class="rating">
                                            <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul>
                                    <li>
                                        Price
                                        <div class="rating">
                                            <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i><i class="icon-smile"></i>
                                        </div>
                                    </li>
                                    <li>
                                        Quality
                                        <div class="rating">
                                            <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- End row -->
                        <hr>
                        <div class="review_strip_single">
                            <img src="~/Content/img/avatar1.jpg" alt="Image" class="rounded-circle">
                            <small> - 10 March 2015 -</small>
                            <h4>Jhon Doe</h4>
                            <p>
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem. Duis quis tempor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus."
                            </p>
                            <div class="rating">
                                <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i><i class="icon-smile"></i>
                            </div>
                        </div>
                        <!-- End review strip -->

                        <div class="review_strip_single">
                            <img src="~/Content/img/avatar3.jpg" alt="Image" class="rounded-circle">
                            <small> - 10 March 2015 -</small>
                            <h4>Jhon Doe</h4>
                            <p>
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem. Duis quis tempor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus."
                            </p>
                            <div class="rating">
                                <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i><i class="icon-smile"></i>
                            </div>
                        </div>
                        <!-- End review strip -->

                        <div class="review_strip_single last">
                            <img src="~/Content/img/avatar2.jpg" alt="Image" class="rounded-circle">
                            <small> - 10 March 2015 -</small>
                            <h4>Jhon Doe</h4>
                            <p>
                                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem quis neque interdum consequat ut sed sem. Duis quis tempor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus."
                            </p>
                            <div class="rating">
                                <i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile voted"></i><i class="icon-smile"></i><i class="icon-smile"></i>
                            </div>
                        </div>
                        <!-- End review strip -->
                    </div>
                </div>
            </div>
            <!--End  single_tour_desc-->
        </div>
        <!--End row -->
    </div>
    <!--End container -->

    <div id="overlay"></div>
    <!-- Mask on input focus -->
</main>